title:            Tech Study Blog
description:      Study note of Software Engineer

#disqus
disqus: True
disqus_shortname: https-sujin729-github-io-infinityandbeyound729-1
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->

#site domain
url: https://sujinsjlee.github.io

# menu
menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'Posts'
    url: '/posts'
  #- title: 'Tags'
  #  url: '/tags'

# Owner/author information
owner:
  name:           SujinLee
  site:           https://github.com/sujinsjlee
  avatar:         images/avatar.jpg
  bio:            "Be useful and Be kind *\n\n
  Here, NOW"
  email:          sjcan2729@gmail.com
  github:         sujinsjlee

social:
  - title: "github"
    url: "https://github.com/sujinsjlee"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/sujinsjlee/"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-150394229-1
google_verify: gVozgHxPlD9PG7tjjp_HrTOh86oq7DyHo8Y1CbW4MKY

timezone:    Asia/Seoul
locale:      ko_KR
future:      true
highlighter: rouge
markdown:    kramdown
lsi: false
incremental: false
sass:
  sass_dir: _sass
  style: compressed


permalink:   /:categories/:year/:month/:day/:title/

# Amount of post to show on home page
paginate: 3

# if true, shows the floatting share buttons
#float_share: true

# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase
titlecase: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-gist
#  - jekyll-avatar
#  - jekyll-seo-tag

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-sitemap, jekyll-feed, jekyll-paginate]
